name: Benchmarking
on:
  push:
    branches:
      - main
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmark
        run: ./dummy.py | tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: test-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customSmallerIsBetter'
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
      - name: Push benchmark result
        run: git push 'https://mkannwischer:${{ secrets.GITHUB_TOKEN }}@github.com/mkannwischer/bench-test.git' gh-pages:gh-pages